nome=str(input("Digite seu nome completo: ")).strip()
print("O seu nome está em analise...")
nome1=nome.upper()
print(f"Seu nome com letras maiusculas: {nome1}")
nome2=nome1.lower()
print(f"Seu nome com letras minusculas: {nome2}")
nome3=(len(nome2)-nome.count(" "))
print(f"Seu nome tem {nome3} letras ao todo")
nome4=nome.find(" ")
print(f"Seu primeiro nome tem {nome4} tantas letras!")